### ISSUE TITLE
Challenge-Responder not launching in Nomad TLS environment

### ISSUE THREAD

**Issue by trissman** [stut/aleff#16]
I am trying to get Aleff going on a cluster where Nomad TLS is in use.  The main Aleff job is running, but I see the following in the STDERR log:

2023/03/07 14:24:30 [INFO] aleff: Running...
2023/03/07 14:24:30 [INFO] [echo.xxxxxxxxxx.com] aleff: Requesting new certificate...
2023/03/07 14:24:30 [INFO] [echo.xxxxxxxxxx.com] acme: Obtaining SAN certificate
2023/03/07 14:24:30 [INFO] [echo.xxxxxxxxxx.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/208950xxxxxx
2023/03/07 14:24:30 [INFO] [echo.xxxxxxxxxx.com] acme: Could not find solver for: tls-alpn-01
2023/03/07 14:24:30 [INFO] [echo.xxxxxxxxxx.com] acme: use http-01 solver
2023/03/07 14:24:30 [INFO] [echo.xxxxxxxxxx.com] acme: Trying to solve HTTP-01
2023/03/07 14:24:30 [INFO] [echo.xxxxxxxxxx.com] aleff: Starting challenge responder...
2023/03/07 14:24:30 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/208950xxxxx
2023/03/07 14:24:31 [WARN] [echo.xxxxxxxxxx.com] aleff: Error: error: one or more domains had a problem:
[echo.xxxxxxxxxx.com] [echo.xxxxxxxxxx.com] acme: error presenting token: tls: failed to find any PEM data in certificate input
2023/03/07 14:24:31 [INFO] aleff: Donw.

I never see the Challenge-Responder job launched in the Nomad UI nor registered as a route in Fabio.  I believe the issue may have to do with Aleff's submission of the job in a TLS environment.

I have templated the necessary .PEM files and set environment variables for them as NOMAD_CACERT, NOMAD_CLIENT_CERT and NOMAD_CLIENT_KEY.  I have checked that the files are being properly created in the secrets directory by inspecting them on the host.  All are world readable within secrets, so I do not think it is a permissions issue.  I have also confirmed that the challenge-responder.hcl job is correctly written to the local directory.  

I am at a loss as to what to try next.  Any idea why the challenge-responder won't launch?

**Comment by stut** [comment]
Thanks for the report. I'm sorry it's taking a while for me to look at this. My test cluster does not use TLS so I'm not currently able to debug the issue, but it will as soon as I can find the time to implement it.

**Comment by stut** [comment]
I am struggling to reproduce this issue. Can you provide any further information?

What I find curious is that the error you're seeing is coming from the acme module which is what talks to Let's Encrypt so I'm not convinced your issue is to do with TLS but without being able to reproduce it I can't be certain.

**Comment by trissman** [comment]
Stuart,

Unfortunately, I can't provide much additional information, but I think 
you are right.  I concluded it was TLS that was causing this behavior 
because I didn't see it when I turned TLS off and then saw it again when I 
turned TLS on.  I then saw similar behavior from Caddy and figured out 
that when Let's Encrypt uses its TLS algorithm (and not just plain HTTP), 
there needs to be a 1-to-1 NAT in place through the firewall and not just 
the port opened by the firewall for responses.  With 1-to-1 NAT, Caddy 
works as expected.  I have not gone back to Aleff since I put the Caddy 
solution in place, but my guess is that this would have fixed Aleff too. 
My apologies for not updating you earlier.

Tom

 
 
 
 
CONTACT INFORMATION
Thomas W. Rissman
McLachlan, Rissman & Doll
676 N. Michigan Avenue, Suite 2800
Chicago, IL  60611
Tel:   (312) 266-1420
Fax:  (312) 266-3330
email:  ***@***.*** 



From:   "Stuart Dallas" ***@***.***>
To:     "stut/aleff" ***@***.***>
Cc:     "trissman" ***@***.***>, "Author" 
***@***.***>
Date:   07/21/2023 03:09 PM
Subject:        Re: [stut/aleff] Challenge-Responder not launching in 
Nomad TLS environment (Issue #16)



I am struggling to reproduce this issue. Can you provide any further 
information?
What I find curious is that the error you're seeing is coming from the 
acme module which is what talks to Let's Encrypt so I'm not convinced your 
issue is to do with TLS but without being able to reproduce it I can't be 
certain.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>
